# Generated by Django 5.0.3 on 2024-03-09 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_id_alter_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='total_rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='book',
            name='total_ratings',
            field=models.IntegerField(default=0),
        ),
    ]
